version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    # Group all dependency updates into one PR
    groups:
      twilight:
        patterns:
          - "twilight*"
      util:
        patterns:
          - "*"
        update-types: minor
