[package]
name = "share-music"
version = "3.2.4"
edition = "2021"
publish = false
build = "build.rs"

[dependencies]
figment = { version = "0.10", features = ["env", "json", "yaml"] }
futures-util = { default-features = false, version = "0.3" }
# fixme: hyper 1.0 removed the client, consider using reqwest instead once they switch to hyper 1.0
hyper = { version = "0.14", features = ["server", "http1", "http2"] }
hyper-rustls = { version = "0.24", features = ["http1", "http2"] }
image = "0.24"
itertools = "0.12"
lazy-regex = "3.1"
parking_lot = "0.12"
prometheus-client = "0.22"
regex = "1.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.24", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json", "parking_lot", "registry", "env-filter"] }
twilight-gateway = "0.15"
twilight-http = "0.15"
twilight-http-ratelimiting = "0.15"
twilight-model = "0.15"
twilight-util = { version = "0.15", features = ["builder", "permission-calculator"] }