[package]
name = "share-music"
version = "3.5.3"
edition = "2021"
publish = false
build = "build.rs"

[dependencies]
axum = "0.7"
figment = { version = "0.10", features = ["env", "json", "yaml"] }
futures-util = { default-features = false, version = "0.3" }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls-native-roots", "http2", "charset", "json"] }
image = "0.25"
itertools = "0.13"
lazy-regex = "3.1"
parking_lot = "0.12"
prometheus-client = "0.22"
regex = "1.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.40", features = ["full"] }
this-state = "0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json", "parking_lot", "registry", "env-filter"] }
twilight-gateway = "0.15"
twilight-http = "0.15"
twilight-http-ratelimiting = "0.15"
twilight-model = "0.15"
twilight-util = { version = "0.15", features = ["builder", "permission-calculator"] }
url = "2.5"
