volumes:
  pg-data:

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
    - "5432:5432"
    volumes:
    - pg-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: share-music
      POSTGRES_PASSWORD: share-music
