/*
 * Copyright (c) 2021-2026 tooboredtocode
 * All Rights Reserved
 */

//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use super::sea_orm_active_enums::CommandSource;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "command_usage")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub interaction_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub original_url: String,
    pub command_source: CommandSource,
    pub guild_id: Option<i64>,
    pub channel_id: Option<i64>,
    pub user_id: Option<i64>,
    pub song_link_url: String,
    pub data_cached: bool,
    pub kind: Option<String>,
    pub artist: Option<String>,
    pub title: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
