/*
 * Copyright (c) 2021-2026 tooboredtocode
 * All Rights Reserved
 */

//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "command_source")]
pub enum CommandSource {
    #[sea_orm(string_value = "share")]
    Share,
    #[sea_orm(string_value = "find_links")]
    FindLinks,
}
